spring:
  application:
    name: zuul-server
    # nombre de aplicación
  output:
    ansi:
      enabled: always
      # formatea la consola de arranque para mostrar colores como en el IDE STS

server:
  port: 8090
  # puerto por defecto de la aplicación

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
      # registrarse en eureka-server

zuul:
  routes:
    productos:
      service-id: servicio-productos
      path: /api/servicio-productos/**
    items:
      service-id: servicio-items
      path: /api/servicio-items/**
      # enrutamiento dinámico con zuul de los servicios que se conectan.
      # se les antepone un prefijo a su URL seguido de la ruta normal de sus endpoints

hystrix:
command:
  default:
    execution:
      isolation:
        thread:
          timeoutInMilliseconds: 20000
  # configura timeout máximo de espera de Hystrix

ribbon:
  ConnectTimeout: 3000
  ReadTimeout: 10000
  # configura timeout máximo de espera de Ribbon

  # la suma de los dos valores de ribbon debería ser algo inferior a la de hystrix