spring:
  application:
    name: zuul-server
  output:
    ansi:
      enabled: always # formatea la consola de arranque para mostrar colores como en el IDE STS

server:
  port: 8090

# incluir eureka-server
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

# enrutamiento dinámico con zuul
zuul:
  routes:
    productos:
      service-id: servicio-productos
      path: /api/servicio-productos/**
    items:
      service-id: servicio-items
      path: /api/servicio-items/**

# Configurar timeout para Hystrix y Ribbon
#hystrix:
#  command:
#    default:
#      execution:
#        isolation:
#          thread:
#            timeoutInMilliseconds: 20000
#
#ribbon:
#  ConnectTimeout: 3000
#  ReadTimeout: 10000