spring:
  application:
    name: servicio-items
  output:
    ansi:
      enabled: always
      # formatea la consola de arranque para mostrar colores como en el IDE STS

server:
  port: ${PORT:0}
  # puerto por defecto de la aplicación

# al añadir eureka-server ya se incluye ribbon, no es necesario
#servicio-productos:
#  ribbon:
#    listOfServers: localhost:8001,localhost:9001

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
      # registrarse en eureka-server
    instance:
      instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}
      # registrarse en eureka-server con el puerto aleatorios

  # hystrix:
  #  command:
  #    default:
  #      execution:
  #        isolation:
  #          thread:
  #            timeoutInMilliseconds: 20000
  # configura timeout máximo de espera de Hystrix

  #ribbon:
  #  ConnectTimeout: 3000
  #  ReadTimeout: 10000
  # configura timeout máximo de espera de Ribbon

  # la suma de los dos valores de ribbon debería ser algo inferior a la de hystrix