spring:
  application:
    name: servicio-items
  output:
    ansi:
      enabled: always # formatea la consola de arranque para mostrar colores como en el IDE STS

server:
  port: 8002

# Al incluir eureka-server ya se incluye ribbon, no es necesario
#servicio-productos:
#  ribbon:
#    listOfServers: localhost:8001,localhost:9001

# Al incluir eureka-server
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka