spring:
  application:
    name: servicio-productos
  output:
    ansi:
      enabled: always
      # formatea la consola de arranque para mostrar colores como en el IDE STS

server:
  port: ${PORT:0}
  # puerto por defecto de la aplicación, random

# incluir eureka-server
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
  instance:
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}
    # registrarse en eureka-server con el puerto aleatorios